version: '3.1'
services:
  app:
    build: ./hello-world-website
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    links:
      - app