FROM microsoft/aspnetcore-build:2.0 AS build-env

WORKDIR /code

COPY . .

RUN dotnet publish --output /build --configuration Release

FROM microsoft/aspnetcore:2.0
WORKDIR /app

COPY --from=build-env /build /app

ENTRYPOINT ["dotnet", "hello-world-website.dll"]